// <auto-generated />
using Class13Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Class13Demo.Migrations
{
    [DbContext(typeof(EnrollmentDbContext))]
    [Migration("20181025234458_updatedInitialTableDAte")]
    partial class updatedInitialTableDAte
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Class13Demo.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<int>("Technology");

                    b.HasKey("ID");

                    b.ToTable("Courses");

                    b.HasData(
                        new { ID = 1, Name = "ethics", Price = 300.0, Technology = 0 },
                        new { ID = 2, Name = "Advanced Ninja", Price = 300.0, Technology = 0 }
                    );
                });

            modelBuilder.Entity("Class13Demo.Models.CourseEnrollments", b =>
                {
                    b.Property<int>("CourseID");

                    b.Property<int>("StudentID");

                    b.HasKey("CourseID", "StudentID");

                    b.HasIndex("StudentID");

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("Class13Demo.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("FirstName")
                        .HasMaxLength(15);

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new { ID = 1, Age = 36, FirstName = "Brian", LastName = "Nelson" },
                        new { ID = 2, Age = 33, FirstName = "Eric", LastName = "Nelson" }
                    );
                });

            modelBuilder.Entity("Class13Demo.Models.Transcript", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseID");

                    b.Property<string>("Grade");

                    b.Property<bool>("Pass");

                    b.Property<int>("StudentID");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Transcripts");
                });

            modelBuilder.Entity("Class13Demo.Models.CourseEnrollments", b =>
                {
                    b.HasOne("Class13Demo.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Class13Demo.Models.Student", "Student")
                        .WithMany("Courses")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Class13Demo.Models.Transcript", b =>
                {
                    b.HasOne("Class13Demo.Models.Course", "Course")
                        .WithMany("Transcripts")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Class13Demo.Models.Student", "Student")
                        .WithMany("Transcripts")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
